In [16]:
from transformers import BertTokenizer, BertModel


In [20]:
sequence_a = "This is the first sentence for self attention between all tokens of A"
sequence_b = "This is the first sentence for self attention between all tokens of B"
sequence_c = "This is the first sentence for self attention between all tokens of A"
sequence_d = "This is the first sentence for self attention between all tokens of B"
# Tokenize the sequences and add special tokens
tokens_a = tokenizer.tokenize(sequence_a)
tokens_b = tokenizer.tokenize(sequence_b)

tokens = ['[CLS]'] + tokens_a + ['[SEP]'] + tokens_b + ['[SEP]']

In [22]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokens = tokenizer(text, return_tensors='pt',padding=True)

In [23]:
tokenizer

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [24]:
tokens

{'input_ids': tensor([[  101,  2023,  2003,  1996,  2034,  6741,  1997, 14324,  2944,  1012,
           102,     0,     0,     0,     0,     0,     0,     0],
        [  101,  2182,  1045,  2031,  7718,  2367,  6741,  1997,  7861,  8270,
          4667,  6741,  1998, 28024,  2169,  6741,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [4]:
print("These are tokens!", tokens)
for token in tokens[0]:
    print("This are decoded tokens!", tokenizer.decode([token]))

These are tokens! tensor([[  101,  2023,  2003,  1996,  2034,  6741,  1997, 14324,  2944,  1012,
          2182,  1045,  2031,  7718,  2367,  6741,  1997,  7861,  8270,  4667,
          6741,  1998, 28024,  2169,  6741,  1012,   102]])
This are decoded tokens! [CLS]
This are decoded tokens! this
This are decoded tokens! is
This are decoded tokens! the
This are decoded tokens! first
This are decoded tokens! layer
This are decoded tokens! of
This are decoded tokens! bert
This are decoded tokens! model
This are decoded tokens! .
This are decoded tokens! here
This are decoded tokens! i
This are decoded tokens! have
This are decoded tokens! tested
This are decoded tokens! different
This are decoded tokens! layer
This are decoded tokens! of
This are decoded tokens! em
This are decoded tokens! ##bed
This are decoded tokens! ##ding
This are decoded tokens! layer
This are decoded tokens! and
This are decoded tokens! replicate
This are decoded tokens! each
This are decoded tokens! layer
This are

In [5]:
model = BertModel.from_pretrained("bert-base-uncased")


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
print(model.embeddings.word_embeddings(tokens))


tensor([[[ 1.3630e-02, -2.6490e-02, -2.3503e-02,  ...,  8.6805e-03,
           7.1340e-03,  1.5147e-02],
         [-5.7095e-02,  1.5283e-02, -4.6868e-03,  ..., -3.2484e-03,
           9.7317e-05,  9.4175e-03],
         [-3.6044e-02, -2.4606e-02, -2.5735e-02,  ...,  3.3691e-03,
          -1.8300e-03,  2.6855e-02],
         ...,
         [ 2.3948e-02, -6.0697e-02, -5.0205e-02,  ..., -2.2587e-02,
          -1.8335e-02, -2.7846e-02],
         [-2.0745e-02, -1.9870e-03, -1.1789e-02,  ...,  1.2760e-02,
           2.0031e-02,  2.5873e-02],
         [-1.4521e-02, -9.9615e-03,  6.0263e-03,  ..., -2.5035e-02,
           4.6379e-03, -1.5378e-03]]], grad_fn=<EmbeddingBackward0>)


In [7]:
print(model.embeddings.word_embeddings(tokens).shape)

torch.Size([1, 27, 768])


In [9]:
for e in model.embeddings.word_embeddings(tokens)[0]:
    print("This is an embedding!", e)

This is an embedding! tensor([ 1.3630e-02, -2.6490e-02, -2.3503e-02, -7.7876e-03,  8.5892e-03,
        -7.6645e-03, -9.8808e-03,  6.0184e-03,  4.6921e-03, -3.0984e-02,
         1.8883e-02, -6.0093e-03, -1.6652e-02,  1.1684e-02, -3.6245e-02,
         8.3482e-03, -1.2112e-03,  1.0322e-02,  1.6692e-02, -3.0354e-02,
        -1.2372e-02, -2.5173e-02, -8.9602e-03,  8.1994e-03, -2.0011e-02,
        -1.5901e-02, -3.8394e-03,  1.4241e-03,  7.0500e-03,  1.6092e-03,
        -2.7764e-03,  9.4931e-03, -2.2768e-02,  1.9317e-02, -1.3442e-02,
        -2.3763e-02, -1.4617e-02,  9.7735e-03, -2.2428e-03,  3.0642e-02,
         6.7829e-03, -2.6471e-03, -1.8553e-02, -1.2363e-02,  7.6489e-03,
        -2.5461e-03, -3.1498e-01,  6.3761e-03,  4.8914e-02, -7.7636e-03,
         6.0919e-02,  2.1346e-02, -3.9741e-02,  2.2853e-01,  2.6502e-02,
        -1.0144e-03, -7.8480e-03, -1.9995e-03,  1.7057e-02, -3.3270e-02,
         4.5421e-03,  6.1751e-03, -1.0077e-01, -2.0973e-02, -1.4512e-04,
        -9.6657e-03,  1.0871e

In [10]:
import torch

In [11]:
seq_length = tokens.size(1)
print(seq_length)

27


In [12]:
position_ids = torch.arange(seq_length, dtype=torch.long)
position_ids = position_ids.unsqueeze(0).expand_as(tokens)

In [17]:
tokens

tensor([[  101,  2023,  2003,  1996,  2034,  6741,  1997, 14324,  2944,  1012,
          2182,  1045,  2031,  7718,  2367,  6741,  1997,  7861,  8270,  4667,
          6741,  1998, 28024,  2169,  6741,  1012,   102]])

In [13]:
position_ids

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [14]:
positional_embedding = model.embeddings.position_embeddings(position_ids)

In [15]:
positional_embedding

tensor([[[ 1.7505e-02, -2.5631e-02, -3.6642e-02,  ...,  3.3437e-05,
           6.8312e-04,  1.5441e-02],
         [ 7.7580e-03,  2.2613e-03, -1.9444e-02,  ...,  2.8910e-02,
           2.9753e-02, -5.3247e-03],
         [-1.1287e-02, -1.9644e-03, -1.1573e-02,  ...,  1.4908e-02,
           1.8741e-02, -7.3140e-03],
         ...,
         [-9.6958e-03,  8.5762e-03, -1.9105e-02,  ...,  2.0086e-02,
           2.8365e-03, -2.6437e-04],
         [-3.9899e-03,  1.3620e-02, -1.7801e-02,  ...,  1.1817e-02,
           1.1702e-03,  1.6589e-03],
         [-1.4377e-02,  8.0714e-03, -4.2855e-03,  ..., -1.4862e-03,
           1.2234e-02, -1.5326e-03]]], grad_fn=<EmbeddingBackward0>)

In [16]:
model.embeddings.position_embedding_type

'absolute'