In [2]:
class Test:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
obj1 = Test('Raj', 28)

In [3]:
obj1.name, obj1.age

('Raj', 28)

In [1]:
import numpy as np
class DenseLayer:
    def __init__(self, n_inputs, n_outputs):
        self.weights = 0.01 * np.random.randn(n_inputs, n_outputs)
        self.bias = np.zeros(n_outputs) 
    
    def forward(self, input):
        self.output = np.dot(input, self.weights) + self.bias

In [2]:
from nnfs.datasets import spiral_data
X, y = spiral_data(samples=100, classes=3) 
dense1 = DenseLayer(2, 3)
dense1.forward(X)
print(dense1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.06549890e-04  3.20034466e-05  7.73949779e-05]
 [-2.02001515e-04  1.01367235e-04  5.07800222e-04]
 [-3.60116319e-04  1.47358882e-04  6.09342164e-04]
 [-2.67486514e-04  1.72695339e-04  1.01373084e-03]]
